parameters:
  elastic.config.required.fields: ['hosts']

services:
  elastic.client:
    class: Elasticsearch\Client
    factory: ['@elastic.client.factory', getClient]
    arguments:
      - '@app.config'
  elastic.client.factory:
    class: Vain\Elastic\Client\Factory\ElasticClientFactory